<?php 

	include "page.class";

	$Sample = new Page; 

	$Content = "<p>This page was generated by a the Page class</p>";

	$Sample->Title = "Using Classes in PHP";
	$Sample->Keywords = "PHP, Classes";
	$Sample->SetContent( $Content );

	$Sample->Display();

?>